#!/usr/bin/env bash
set -xe

cd "$(dirname "$(realpath "$0")")"


# Download and install qt-creator + ROS plugin
curl -LO "https://github.com/qt-creator/qt-creator/releases/download/v8.0.1/qtcreator-Linux-2838347900.7z"
curl -LO "https://github.com/ros-industrial/ros_qtc_plugin/releases/download/8.1/ROSProjectManager-8.1-Linux-x86_64.zip"

# Non-sudo installation throws exception
mkdir -p _opt_qtcreator
7z x qtcreator-Linux-2838347900.7z -o_opt_qtcreator # will need artefact and 7z support
7z x ROSProjectManager-8.1-Linux-x86_64.zip -o_opt_qtcreator
#sudo chown root:root _opt_qtcreator -R
# Environment Setup
cp env.sh _opt_qtcreator/.env.sh

# Use _opt_qtcreator for readability, rename to _opt b/c it's expected by Dockerfile
mv _opt_qtcreator _opt

